In [1]:
import numpy as np

## Numpy Knowledge

### 1. Data Type

In [2]:
a = [1, "hello", 0.4] # normal python list

In [7]:
a = np.array([1,"hello"])
print(a)
print(a.dtype)
a +=1

['1' 'hello']
<U21


UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

In [43]:
a = np.array([[1,2,3,4],
              [5,6,7,8]])
print(a)
print(a.dtype)
a += 1
print(a)

[[1 2 3 4]
 [5 6 7 8]]
int64
[[2 3 4 5]
 [6 7 8 9]]


### 2. Fixed Length, Fixed Datatype Array

In [54]:
a = [1,2,3,4]
a.append(3)
print(a)

[1, 2, 3, 4, 3]


In [55]:
a = np.array([1,2,3,4])
a.append(5)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [56]:
np.hstack([a, a])

array([1, 2, 3, 4, 1, 2, 3, 4])

In [65]:
a = np.array([[1,2,3],
            [4,5,6]])

b = np.array([[2,],[3,]])
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[2]
 [3]]


In [66]:
np.hstack([a,b])

array([[1, 2, 3, 2],
       [4, 5, 6, 3]])

In [67]:
b = np.array([[1.5],[4.5]])

In [68]:
c = np.hstack([a,b])
print(c)
print(c.dtype)

[[1.  2.  3.  1.5]
 [4.  5.  6.  4.5]]
float64


### 3. Less for

In [32]:
a = [0 for _ in range(100)]
print(a)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [34]:
np.zeros(100, dtype= np.int64)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### 4. Array Calculation

In [37]:
a = np.array([[1,2,3],
            [4,5,6]])
print(a)
a += 10
print(a)

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]
